"""requirements.txt lockfile validation (validate-if-present)."""

from __future__ import annotations

import re
from pathlib import Path

from ._common import _rel_for_audit
from ._findings import Finding
from ._shape import Shape

_PIN_RE = re.compile(r"^[A-Za-z][\w.\-]*\s*==\s*", re.MULTILINE)


def _is_real_lockfile(path: Path) -> bool:
    """A real pip-compile lockfile has the autogen header or at least one pin.

    An empty or comments-only file is treated as a placeholder, not a lockfile.
    pip-compile output always starts with a header containing the literal
    string `pip-compile`; additionally, it contains at least one pinned
    requirement of the form `name==version`.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    head = text[:1000]
    if "pip-compile" in head or "autogenerated" in head.lower():
        return True
    return bool(_PIN_RE.search(text))


def check_requirements(root: Path, shape: Shape) -> list[Finding]:
    """Lockfiles are optional in racecar canon; if committed, they must be real.

    The canon does not require a requirements.txt. Pyproject is the sole source
    of truth for dependencies. But if a project chooses to commit a
    requirements.txt (snapshot, deployment artifact, CI input), it must be a
    real pip-compile or pip-freeze output -- not an empty placeholder.

    Checks the standard lockfile locations for each shape:
      src/djapp:    requirements.txt at root
      pypkg:        requirements.txt at pypkg/src/
      pypkg+djapp:  requirements.txt at pypkg/src/ AND djapp/

    Each path: if present, validated; if absent, no finding.
    """
    findings: list[Finding] = []
    candidates: list[Path] = []
    if shape.name in ("src", "djapp"):
        candidates.append(root / "requirements.txt")
    if shape.name in ("pypkg", "pypkg+djapp"):
        candidates.append(root / "pypkg" / "src" / "requirements.txt")
    if shape.name == "pypkg+djapp":
        candidates.append(root / "djapp" / "requirements.txt")
    for path in candidates:
        if not path.exists():
            continue  # optional; absence is fine
        if not _is_real_lockfile(path):
            label = _rel_for_audit(root, path)
            findings.append(
                Finding(
                    "Blocker",
                    label,
                    "not-a-lockfile",
                    "committed requirements.txt must be a real pip-compile or pip-freeze output "
                    "(empty or comments-only file is rejected); either populate it or remove it",
                )
            )
    return findings
